---
- hosts: all
  become: yes
  tasks:
    - name: "update apt package cache."
      apt:
        update_cache: yes

    - name: Install Apache HTTP server
      apt:
        name: apache2
        state: present

    - name: "copy the file"
      copy:
        src: index.html
        dest: /var/www/html

    - name: "Start Apache service and enable it"
      service:
        name: apache2
        state: started
        enabled: yes
                             
